name: Documentation

on:
  push:
    branches: 
    - dev
    - amd-staging
    - main
    - amd-mainline
    - 'docs/*'
    - 'release/*'
  pull_request:
    branches: 
    - dev
    - amd-staging
    - main
    - amd-mainline
    - 'docs/*'
    - 'release/*'

jobs:
  call-workflow-passing-data:
    name: Linting
    uses: ROCm/rocm-docs-core/.github/workflows/linting.yml@develop
